---
- name: Make sure apt can use TLS
  apt:
    name: apt-transport-https
    state: present
  when: rundeck_install_apt_transport_https

- name: Install Rundeck apt key
  apt_key:
    url: "{{ rundeck_apt_key_url }}"
    state: present
  when: rundeck_install_apt_key

- name: Install Rundeck apt repository
  copy:
    dest: /etc/apt/sources.list.d/rundeck.list
    content: |
      {{ rundeck_apt_repo }}
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: _rundeck_repo
  when: rundeck_install_apt_repo

- name: Pin Rundeck package version
  copy:
    dest: /etc/apt/preferences.d/rundeck
    content: |
      Package: rundeck
      Pin: version {{ rundeck_version }}
      Pin-Priority: 1002
    mode: u=rw,g=rw,o=r
  when: rundeck_pin_version

- name: Install Rundeck
  apt:
    name: "{{ _rundeck_packages }}"
    update_cache: "{{ _rundeck_repo is changed }}"
    state: present
