---
- name: Prepare
  hosts: rundeck.app
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - python-openssl
          - ca-certificates
        state: present

    - name: Generate localhost private key
      openssl_privatekey:
        path: /etc/ssl/localhost.key

    - name: Generate localhost CSR
      openssl_csr:
        path: /etc/ssl/localhost.csr
        privatekey_path: /etc/ssl/localhost.key
        common_name: localhost

    - name: Generate localhost cert
      openssl_certificate:
        path: /etc/ssl/localhost.crt
        privatekey_path: /etc/ssl/localhost.key
        csr_path: /etc/ssl/localhost.csr
        provider: selfsigned

    - name: Copy localhost cert to trust store
      copy:
        remote_src: true
        src: /etc/ssl/localhost.crt
        dest: /usr/local/share/ca-certificates/localhost.crt
      register: _cert_copy

    - name: Update trusted CA certs
      command: update-ca-certificates
      when: _cert_copy is changed
